name: 'Validate JSON'
description:
  'Validate JSON file(s) with JSON Schema and enforce best practices.'
author: 'Emmanuel Gautier'
branding:
  icon: 'check'
  color: 'green'

inputs:
  files:
    description: 'The JSON file(s) to validate.'
    required: true
  schema:
    description: 'The JSON Schema to validate against.'
    required: false
  strict:
    description: 'Enforce strict validation.'
    required: false
    default: 'false'

outputs:
  valid:
    description: 'Whether the JSON file(s) are valid.'
  # errors:
  #   description: 'The validation errors.'

runs:
  using: node20
  main: dist/index.js
